import Foundation

public struct StoredAttachment: Equatable, Sendable {
    public let relativePath: String
    public let fileName: String
    public let byteCount: Int

    public var markdownDestination: String { relativePath }
}

public enum AttachmentStorageError: Error, Equatable, LocalizedError, Sendable {
    case emptyData
    case unsupportedFile(String)
    case invalidPath(String)
    case missingAttachment(String)
    case destinationExists(String)

    public var errorDescription: String? {
        switch self {
        case .emptyData:
            "The attachment is empty."
        case .unsupportedFile(let name):
            "The attachment must be a file: \(name)"
        case .invalidPath(let path):
            "The attachment path is invalid: \(path)"
        case .missingAttachment(let path):
            "The attachment could not be found: \(path)"
        case .destinationExists(let path):
            "An attachment already exists at: \(path)"
        }
    }
}

public enum MarkdownAttachmentIndex {
    // Keep the lifetime index and the editor on the same syntax. In particular,
    // labels generated by escapedLabel may contain an escaped closing bracket.
    static let referenceRegex = try! NSRegularExpression(
        pattern: #"(!?)\[((?:\\.|[^\]\\\n])*)\]\(((?:\.\./)*Attachments/[^)\n]+)\)"#
    )

    public static func referencedPaths(in markdown: String) -> Set<String> {
        let ns = markdown as NSString
        let range = NSRange(location: 0, length: ns.length)
        var paths: Set<String> = []
        referenceRegex.enumerateMatches(in: markdown, range: range) { match, _, _ in
            guard let match else { return }
            let raw = ns.substring(with: match.range(at: 3))
            if let canonical = canonicalPath(raw) {
                paths.insert(canonical)
            }
        }
        return paths
    }

    public static func referencedPaths(in items: [Item]) -> Set<String> {
        items.reduce(into: Set<String>()) { result, item in
            result.formUnion(referencedPaths(in: item.body))
        }
    }

    static func canonicalPath(_ path: String) -> String? {
        var value = path.removingPercentEncoding ?? path
        while value.hasPrefix("../") { value.removeFirst(3) }
        let parts = value.split(separator: "/", omittingEmptySubsequences: false)
        guard parts.count == 2, parts[0] == "Attachments", !parts[1].isEmpty,
              parts[1] != ".", parts[1] != "..", !parts[1].contains("\\"),
              !value.contains("\0") else { return nil }
        return value
    }

    static func isSafeRelativePath(_ path: String) -> Bool { canonicalPath(path) != nil }

    static func fileURL(_ path: String, root: URL = StorageRoot.defaultListsDirectory()) -> URL? {
        guard let canonical = canonicalPath(path) else { return nil }
        let expectedDirectory = root.resolvingSymlinksInPath().appendingPathComponent("Attachments")
        let directory = expectedDirectory.resolvingSymlinksInPath()
        guard directory.path == expectedDirectory.path else { return nil }
        let url = directory.appendingPathComponent(String(canonical.dropFirst("Attachments/".count))).resolvingSymlinksInPath()
        let allowed = expectedDirectory.path + "/"
        return url.path.hasPrefix(allowed) ? url : nil
    }

}

extension FileStore {
    private var attachmentsDirectory: URL {
        root.appendingPathComponent("Attachments", isDirectory: true)
    }

    private var attachmentTrashDirectory: URL {
        root.appendingPathComponent(".attachments-trash", isDirectory: true)
    }

    private func validatedAttachmentDirectory(_ directory: URL) throws -> URL {
        let expected = root.resolvingSymlinksInPath()
            .appendingPathComponent(directory.lastPathComponent, isDirectory: true)
        guard expected.resolvingSymlinksInPath().path == expected.path else {
            throw AttachmentStorageError.invalidPath(directory.lastPathComponent)
        }
        return expected
    }

    public func importAttachment(
        data: Data,
        originalFileName: String?,
        preferredExtension: String? = nil
    ) throws -> StoredAttachment {
        guard data.isEmpty == false else { throw AttachmentStorageError.emptyData }
        try ensureRoot()
        try FileManager.default.createDirectory(
            at: attachmentsDirectory,
            withIntermediateDirectories: true
        )

        let ext = sanitizedExtension(
            preferredExtension?.nilIfEmpty
                ?? originalFileName.map { URL(fileURLWithPath: $0).pathExtension }?.nilIfEmpty
                ?? "bin"
        )
        let fileName = "\(UUID().uuidString.lowercased()).\(ext)"
        guard let destination = MarkdownAttachmentIndex.fileURL("Attachments/" + fileName, root: root) else {
            throw AttachmentStorageError.invalidPath(fileName)
        }
        try data.write(to: destination, options: [.atomic])
        return StoredAttachment(
            relativePath: "Attachments/\(fileName)",
            fileName: fileName,
            byteCount: data.count
        )
    }

    public func importAttachment(fileURL: URL, preferredFileName: String? = nil) throws -> StoredAttachment {
        // Copy the selected file's contents, not a symbolic link that would
        // depend on the external source remaining available after import.
        let source = fileURL.resolvingSymlinksInPath()
        let sourceValues = try source.resourceValues(forKeys: [.isRegularFileKey, .fileSizeKey])
        guard sourceValues.isRegularFile == true else {
            throw AttachmentStorageError.unsupportedFile(fileURL.lastPathComponent)
        }
        guard (sourceValues.fileSize ?? 0) > 0 else { throw AttachmentStorageError.emptyData }
        try ensureRoot()
        try FileManager.default.createDirectory(at: attachmentsDirectory, withIntermediateDirectories: true)
        let ext = sanitizedExtension(fileURL.pathExtension.nilIfEmpty ?? "bin")
        let name = preferredFileName ?? "\(UUID().uuidString.lowercased()).\(ext)"
        guard name == URL(fileURLWithPath: name).lastPathComponent,
              MarkdownAttachmentIndex.canonicalPath("Attachments/" + name) != nil else { throw AttachmentStorageError.invalidPath(name) }
        guard let destination = MarkdownAttachmentIndex.fileURL("Attachments/" + name, root: root) else {
            throw AttachmentStorageError.invalidPath(name)
        }
        guard !FileManager.default.fileExists(atPath: destination.path) else { throw AttachmentStorageError.destinationExists(name) }
        let staging = attachmentsDirectory.appendingPathComponent(".import-" + UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: staging) }
        try FileManager.default.copyItem(at: source, to: staging)
        let count = try staging.resourceValues(forKeys: [.fileSizeKey]).fileSize ?? 0
        guard count > 0 else { throw AttachmentStorageError.emptyData }
        try FileManager.default.moveItem(at: staging, to: destination)
        return StoredAttachment(relativePath: "Attachments/" + name, fileName: name, byteCount: count)
    }

    public func attachmentURL(for relativePath: String) throws -> URL {
        guard let candidate = MarkdownAttachmentIndex.fileURL(relativePath, root: root) else {
            throw AttachmentStorageError.invalidPath(relativePath)
        }
        let attachmentsRoot = root.resolvingSymlinksInPath().appendingPathComponent("Attachments").path + "/"
        guard candidate.path.hasPrefix(attachmentsRoot) else {
            throw AttachmentStorageError.invalidPath(relativePath)
        }
        guard FileManager.default.fileExists(atPath: candidate.path) else {
            throw AttachmentStorageError.missingAttachment(relativePath)
        }
        guard try candidate.resourceValues(forKeys: [.isRegularFileKey]).isRegularFile == true else {
            throw AttachmentStorageError.unsupportedFile(candidate.lastPathComponent)
        }
        return candidate
    }

    /// Moves unreferenced files aside rather than deleting them. The trash is
    /// included in full-library exports, so an over-eager cleanup remains
    /// recoverable even before the file is restored in-app.
    public func quarantineUnreferencedAttachments(
        referencedPaths: Set<String>
    ) throws -> [String] {
        let attachmentsDirectory = try validatedAttachmentDirectory(self.attachmentsDirectory)
        let attachmentTrashDirectory = try validatedAttachmentDirectory(self.attachmentTrashDirectory)
        guard FileManager.default.fileExists(atPath: attachmentsDirectory.path) else { return [] }
        try FileManager.default.createDirectory(
            at: attachmentTrashDirectory,
            withIntermediateDirectories: true
        )
        let urls = try FileManager.default.contentsOfDirectory(
            at: attachmentsDirectory,
            includingPropertiesForKeys: [.isRegularFileKey],
            options: [.skipsHiddenFiles]
        )
        var quarantined: [String] = []
        for source in urls.sorted(by: { $0.lastPathComponent < $1.lastPathComponent }) {
            guard try source.resourceValues(forKeys: [.isRegularFileKey]).isRegularFile == true else { continue }
            let relativePath = "Attachments/\(source.lastPathComponent)"
            guard referencedPaths.contains(relativePath) == false else { continue }
            let destination = attachmentTrashDirectory.appendingPathComponent(source.lastPathComponent)
            if FileManager.default.fileExists(atPath: destination.path) {
                throw AttachmentStorageError.destinationExists(source.lastPathComponent)
            }
            try FileManager.default.moveItem(at: source, to: destination)
            quarantined.append(relativePath)
        }
        return quarantined
    }

    public func restoreQuarantinedAttachment(fileName: String) throws -> StoredAttachment {
        let safeName = URL(fileURLWithPath: fileName).lastPathComponent
        guard safeName == fileName,
              MarkdownAttachmentIndex.canonicalPath("Attachments/" + safeName) == "Attachments/" + safeName else {
            throw AttachmentStorageError.invalidPath(fileName)
        }
        let attachmentsDirectory = try validatedAttachmentDirectory(self.attachmentsDirectory)
        let attachmentTrashDirectory = try validatedAttachmentDirectory(self.attachmentTrashDirectory)
        let source = attachmentTrashDirectory.appendingPathComponent(safeName)
        guard source.resolvingSymlinksInPath().path == source.path else {
            throw AttachmentStorageError.invalidPath(fileName)
        }
        guard FileManager.default.fileExists(atPath: source.path) else {
            throw AttachmentStorageError.missingAttachment(fileName)
        }
        guard try source.resourceValues(forKeys: [.isRegularFileKey]).isRegularFile == true else {
            throw AttachmentStorageError.unsupportedFile(fileName)
        }
        try FileManager.default.createDirectory(at: attachmentsDirectory, withIntermediateDirectories: true)
        let destination = attachmentsDirectory.appendingPathComponent(safeName)
        guard FileManager.default.fileExists(atPath: destination.path) == false else {
            throw AttachmentStorageError.destinationExists("Attachments/\(safeName)")
        }
        try FileManager.default.moveItem(at: source, to: destination)
        let byteCount = (try? destination.resourceValues(forKeys: [.fileSizeKey]).fileSize) ?? 0
        return StoredAttachment(
            relativePath: "Attachments/\(safeName)",
            fileName: safeName,
            byteCount: byteCount
        )
    }

    private func sanitizedExtension(_ raw: String) -> String {
        let allowed = raw.lowercased().unicodeScalars.filter {
            CharacterSet.alphanumerics.contains($0)
        }
        let value = String(String.UnicodeScalarView(allowed))
        return String(value.prefix(12)).nilIfEmpty ?? "bin"
    }
}
